name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Update Environment
      run: sudo apt update -y && sudo apt upgrade -y

    - name: Install Dependencies
      run: |
        sudo apt install -y git-core gnupg flex bc bison build-essential zip \
        curl zlib1g-dev g++-multilib libc6-dev-i386 lib32ncurses5-dev \
        xsltproc unzip python2 python3 python3-pip python3-dev \
        python-is-python3 schedtool ccache libtinfo5 libncurses5 lzop tmux \
        patchelf git-lfs ripgrep clang-11 &> /dev/null

    - name: Download Neutron Toolchain
      run: bash build.sh --tools

    - name: Build Nova
      run: bash build.sh --build

    - name: Upload kernel
      uses: actions/upload-artifact@v3
      with:
        name: NoVA-Begonia
        path: NoVA-Begonia-4.14.*.zip
